server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mywallet
    username: szabo-peter
    password: 123456
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
